ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "HANDOVER_NOT_FOUND": "HANDOVER_NOT_FOUND",
    "HANDOVER_NOT_PENDING": "HANDOVER_NOT_PENDING",
    "HANDOVER_NOT_FROM_OWNER": "HANDOVER_NOT_FROM_OWNER",
    "HANDOVER_NOT_TO_OWNER": "HANDOVER_NOT_TO_OWNER",
    "HANDOVER_TASK_NOT_OWNED": "HANDOVER_TASK_NOT_OWNED",
    "HANDOVER_TASK_NOT_OPEN": "HANDOVER_TASK_NOT_OPEN",
    "HANDOVER_EMPTY_ITEMS": "HANDOVER_EMPTY_ITEMS",
    "HANDOVER_RECEIVER_REQUIRED": "HANDOVER_RECEIVER_REQUIRED",
    "HANDOVER_SITE_NOTE_REQUIRED": "HANDOVER_SITE_NOTE_REQUIRED",
    "HANDOVER_ETA_REQUIRED": "HANDOVER_ETA_REQUIRED",
    "HANDOVER_ITEM_RESULT_MISMATCH": "HANDOVER_ITEM_RESULT_MISMATCH"
}
