ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "HANDOVER_NOT_FOUND": "HANDOVER_NOT_FOUND",
    "HANDOVER_NOT_PENDING": "HANDOVER_NOT_PENDING",
    "HANDOVER_FORBIDDEN": "HANDOVER_FORBIDDEN",
    "HANDOVER_TASK_FINISHED": "HANDOVER_TASK_FINISHED",
    "HANDOVER_ALREADY_PENDING": "HANDOVER_ALREADY_PENDING",
}
